/* export const GET_VIDEOGAMES = "GET_VIDEOGAMES";  */
export const FETCH_VIDEOGAMES_SUCCESS = "FETCH_VIDEOGAMES_SUCCESS";
export const FETCH_VIDEOGAMES_ERROR = "FETCH_VIDEOGAMES_ERROR";
export const GET_DETAIL_VIDEOGAME = "GET_DETAIL_VIDEOGAME";
export const EMPTY_DETAIL_VIDEOGAME = "EMPTY_DETAIL_VIDEOGAME";
export const SEARCH_VIDEOGAMES = "SEARCH_VIDEOGAMES";
export const GET_GENRES = "GET_GENRES";
export const ORDER_VIDEOGAMES = "ORDER_VIDEOGAMES";
export const FILTER_VIDEOGAMES = "FILTER_VIDEOGAMES";
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const ORIGEN_FILTER_VIDEOGAMES = "ORIGEN_FILTER_VIDEOGAMES";
export const FILTER_PLATFORM = "FILTER_PLATFORM";
export const EMPTY_FILTERED_VIDEOGAMES = "EMPTY_FILTERED_VIDEOGAMES";


